services:
  redis1:
    image: redis:latest
    container_name: redis1
    ports:
      - "6379:6379"

  redis2:
    image: redis:latest
    container_name: redis2
    ports:
      - "6380:6379"

  redis3:
    image: redis:latest
    container_name: redis3
    ports:
      - "6381:6379"